version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexa_crm
    volumes:
      - nexa_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./nexa_backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/nexa_crm
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./nexa_backend:/app
      - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run start:dev"

  frontend:
    build:
      context: ./nexa_frontend
      dockerfile: Dockerfile
    restart: always
    ports:
        - "8081:8081"   # mapeia a porta do container para host
        - "19000:19000" # Dev Server (QR Code)
        - "19001:19001" # Metro Bundler
    volumes:
      - ./nexa_frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexa.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  nexa_db_data: